// <auto-generated />
using System;
using API.src.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AdventureWorksContext))]
    [Migration("20251212101451_AAA")]
    partial class AAA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.src.models.AuthToken", b =>
                {
                    b.Property<int>("AuthTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthTokenID"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuthTokenID");

                    b.ToTable("AuthToken");
                });

            modelBuilder.Entity("API.src.models.BusinessEntity", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for all customers, vendors, and employees.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessEntityID"));

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<Guid>("rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityID")
                        .HasName("PK_BusinessEntity_BusinessEntityID");

                    b.HasIndex(new[] { "rowguid" }, "AK_BusinessEntity_rowguid")
                        .IsUnique();

                    b.ToTable("BusinessEntity", "Person", t =>
                        {
                            t.HasComment("Source of the ID that connects vendors, customers, and employees with address and contact information.");
                        });
                });

            modelBuilder.Entity("API.src.models.Department", b =>
                {
                    b.Property<short>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasComment("Primary key for Department records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DepartmentID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the group to which the department belongs.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the department.");

                    b.HasKey("DepartmentID")
                        .HasName("PK_Department_DepartmentID");

                    b.HasIndex(new[] { "Name" }, "AK_Department_Name")
                        .IsUnique();

                    b.ToTable("Department", "HumanResources", t =>
                        {
                            t.HasComment("Lookup table containing the departments within the Adventure Works Cycles company.");
                        });
                });

            modelBuilder.Entity("API.src.models.EmailAddress", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Primary key. Person associated with this email address.  Foreign key to Person.BusinessEntityID");

                    b.Property<int>("EmailAddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key. ID of this email address.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailAddressID"));

                    b.Property<string>("EmailAddress1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailAddress")
                        .HasComment("E-mail address for the person.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<Guid>("rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityID", "EmailAddressID")
                        .HasName("PK_EmailAddress_BusinessEntityID_EmailAddressID");

                    b.HasIndex(new[] { "EmailAddress1" }, "IX_EmailAddress_EmailAddress");

                    b.ToTable("EmailAddress", "Person", t =>
                        {
                            t.HasComment("Where to send a person email.");
                        });
                });

            modelBuilder.Entity("API.src.models.Employee", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Primary key for Employee records.  Foreign key to BusinessEntity.BusinessEntityID.");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasComment("Date of birth.");

                    b.Property<bool>("CurrentFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("0 = Inactive, 1 = Active");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength()
                        .HasComment("M = Male, F = Female");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasComment("Employee hired on this date.");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Work title such as Buyer or Sales Representative.");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Network login.");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength()
                        .HasComment("M = Married, S = Single");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Unique national identification number such as a social security number.");

                    b.Property<short?>("OrganizationLevel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasComputedColumnSql("([OrganizationNode].[GetLevel]())", false)
                        .HasComment("The depth of the employee in the corporate hierarchy.");

                    b.Property<bool>("SalariedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Job classification. 0 = Hourly, not exempt from collective bargaining. 1 = Salaried, exempt from collective bargaining.");

                    b.Property<short>("SickLeaveHours")
                        .HasColumnType("smallint")
                        .HasComment("Number of available sick leave hours.");

                    b.Property<short>("VacationHours")
                        .HasColumnType("smallint")
                        .HasComment("Number of available vacation hours.");

                    b.Property<Guid>("rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityID")
                        .HasName("PK_Employee_BusinessEntityID");

                    b.HasIndex(new[] { "LoginID" }, "AK_Employee_LoginID")
                        .IsUnique();

                    b.HasIndex(new[] { "NationalIDNumber" }, "AK_Employee_NationalIDNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "rowguid" }, "AK_Employee_rowguid")
                        .IsUnique();

                    b.ToTable("Employee", "HumanResources", t =>
                        {
                            t.HasComment("Employee information such as salary, department, and title.");

                            t.HasTrigger("dEmployee");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("API.src.models.EmployeeDepartmentHistory", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Employee identification number. Foreign key to Employee.BusinessEntityID.");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasComment("Date the employee started work in the department.");

                    b.Property<short>("DepartmentID")
                        .HasColumnType("smallint")
                        .HasComment("Department in which the employee worked including currently. Foreign key to Department.DepartmentID.");

                    b.Property<byte>("ShiftID")
                        .HasColumnType("tinyint")
                        .HasComment("Identifies which 8-hour shift the employee works. Foreign key to Shift.Shift.ID.");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasComment("Date the employee left the department. NULL = Current department.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("BusinessEntityID", "StartDate", "DepartmentID", "ShiftID")
                        .HasName("PK_EmployeeDepartmentHistory_BusinessEntityID_StartDate_DepartmentID");

                    b.HasIndex(new[] { "DepartmentID" }, "IX_EmployeeDepartmentHistory_DepartmentID");

                    b.HasIndex(new[] { "ShiftID" }, "IX_EmployeeDepartmentHistory_ShiftID");

                    b.ToTable("EmployeeDepartmentHistory", "HumanResources", t =>
                        {
                            t.HasComment("Employee department transfers.");
                        });
                });

            modelBuilder.Entity("API.src.models.EmployeePayHistory", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Employee identification number. Foreign key to Employee.BusinessEntityID.");

                    b.Property<DateTime>("RateChangeDate")
                        .HasColumnType("datetime")
                        .HasComment("Date the change in pay is effective");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<byte>("PayFrequency")
                        .HasColumnType("tinyint")
                        .HasComment("1 = Salary received monthly, 2 = Salary received biweekly");

                    b.Property<decimal>("Rate")
                        .HasColumnType("money")
                        .HasComment("Salary hourly rate.");

                    b.HasKey("BusinessEntityID", "RateChangeDate")
                        .HasName("PK_EmployeePayHistory_BusinessEntityID_RateChangeDate");

                    b.ToTable("EmployeePayHistory", "HumanResources", t =>
                        {
                            t.HasComment("Employee pay history.");
                        });
                });

            modelBuilder.Entity("API.src.models.JobCandidate", b =>
                {
                    b.Property<int>("JobCandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for JobCandidate records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCandidateID"));

                    b.Property<int?>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Employee identification number if applicant was hired. Foreign key to Employee.BusinessEntityID.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .HasColumnType("xml")
                        .HasComment("Résumé in XML format.");

                    b.HasKey("JobCandidateID")
                        .HasName("PK_JobCandidate_JobCandidateID");

                    b.HasIndex(new[] { "BusinessEntityID" }, "IX_JobCandidate_BusinessEntityID");

                    b.ToTable("JobCandidate", "HumanResources", t =>
                        {
                            t.HasComment("Résumés submitted to Human Resources by job applicants.");
                        });
                });

            modelBuilder.Entity("API.src.models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("API.src.models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("NotificationID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("API.src.models.Password", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasComment("Password for the e-mail account.");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasComment("Random value concatenated with the password string before the password is hashed.");

                    b.Property<Guid>("rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityID")
                        .HasName("PK_Password_BusinessEntityID");

                    b.ToTable("Password", "Person", t =>
                        {
                            t.HasComment("One way hashed authentication information");
                        });
                });

            modelBuilder.Entity("API.src.models.Person", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Primary key for Person records.");

                    b.Property<string>("AdditionalContactInfo")
                        .HasColumnType("xml")
                        .HasComment("Additional contact information about the person stored in xml format. ");

                    b.Property<string>("Demographics")
                        .HasColumnType("xml")
                        .HasComment("Personal information such as hobbies, and income collected from online shoppers. Used for sales analysis.");

                    b.Property<int>("EmailPromotion")
                        .HasColumnType("int")
                        .HasComment("0 = Contact does not wish to receive e-mail promotions, 1 = Contact does wish to receive e-mail promotions from AdventureWorks, 2 = Contact does wish to receive e-mail promotions from AdventureWorks and selected partners. ");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("First name of the person.");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Last name of the person.");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Middle name or middle initial of the person.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<bool>("NameStyle")
                        .HasColumnType("bit")
                        .HasComment("0 = The data in FirstName and LastName are stored in western style (first name, last name) order.  1 = Eastern style (last name, first name) order.");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength()
                        .HasComment("Primary type of person: SC = Store Contact, IN = Individual (retail) customer, SP = Sales person, EM = Employee (non-sales), VC = Vendor contact, GC = General contact");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Surname suffix. For example, Sr. or Jr.");

                    b.Property<string>("Title")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasComment("A courtesy title. For example, Mr. or Ms.");

                    b.Property<Guid>("rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityID")
                        .HasName("PK_Person_BusinessEntityID");

                    b.HasIndex(new[] { "rowguid" }, "AK_Person_rowguid")
                        .IsUnique();

                    b.HasIndex(new[] { "LastName", "FirstName", "MiddleName" }, "IX_Person_LastName_FirstName_MiddleName");

                    b.HasIndex(new[] { "AdditionalContactInfo" }, "PXML_Person_AddContact");

                    b.HasIndex(new[] { "Demographics" }, "PXML_Person_Demographics");

                    b.HasIndex(new[] { "Demographics" }, "XMLPATH_Person_Demographics");

                    b.HasIndex(new[] { "Demographics" }, "XMLPROPERTY_Person_Demographics");

                    b.HasIndex(new[] { "Demographics" }, "XMLVALUE_Person_Demographics");

                    b.ToTable("Person", "Person", t =>
                        {
                            t.HasComment("Human beings involved with AdventureWorks: employees, customer contacts, and vendor contacts.");

                            t.HasTrigger("iuPerson");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("API.src.models.EmailAddress", b =>
                {
                    b.HasOne("API.src.models.Person", "BusinessEntity")
                        .WithMany("EmailAddress")
                        .HasForeignKey("BusinessEntityID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("API.src.models.Employee", b =>
                {
                    b.HasOne("API.src.models.Person", "BusinessEntity")
                        .WithOne("Employee")
                        .HasForeignKey("API.src.models.Employee", "BusinessEntityID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("API.src.models.EmployeeDepartmentHistory", b =>
                {
                    b.HasOne("API.src.models.Employee", "BusinessEntity")
                        .WithMany("EmployeeDepartmentHistory")
                        .HasForeignKey("BusinessEntityID")
                        .IsRequired();

                    b.HasOne("API.src.models.Department", "Department")
                        .WithMany("EmployeeDepartmentHistory")
                        .HasForeignKey("DepartmentID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("API.src.models.EmployeePayHistory", b =>
                {
                    b.HasOne("API.src.models.Employee", "BusinessEntity")
                        .WithMany("EmployeePayHistory")
                        .HasForeignKey("BusinessEntityID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("API.src.models.JobCandidate", b =>
                {
                    b.HasOne("API.src.models.Employee", "BusinessEntity")
                        .WithMany("JobCandidate")
                        .HasForeignKey("BusinessEntityID");

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("API.src.models.Password", b =>
                {
                    b.HasOne("API.src.models.Person", "BusinessEntity")
                        .WithOne("Password")
                        .HasForeignKey("API.src.models.Password", "BusinessEntityID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("API.src.models.Person", b =>
                {
                    b.HasOne("API.src.models.BusinessEntity", "BusinessEntity")
                        .WithOne("Person")
                        .HasForeignKey("API.src.models.Person", "BusinessEntityID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("API.src.models.BusinessEntity", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("API.src.models.Department", b =>
                {
                    b.Navigation("EmployeeDepartmentHistory");
                });

            modelBuilder.Entity("API.src.models.Employee", b =>
                {
                    b.Navigation("EmployeeDepartmentHistory");

                    b.Navigation("EmployeePayHistory");

                    b.Navigation("JobCandidate");
                });

            modelBuilder.Entity("API.src.models.Person", b =>
                {
                    b.Navigation("EmailAddress");

                    b.Navigation("Employee");

                    b.Navigation("Password");
                });
#pragma warning restore 612, 618
        }
    }
}
